### ISSUE TITLE
User story checklist

### ISSUE THREAD

**Issue by yvonne-liu** [FAC10/week1-ajoy-facx-machine#16]
+ As a client looking to hire a team of developers

- [x] I want to visit your site and immediately see a headline about your team so that I get a concise description of what you have to offer me.

+ As a client looking to hire a team of developers

- [x] I want to visit your site and see a navigation link for 'About, Team, and Contact' so I can quickly navigate to the areas of the site I'd like to visit. 

+ As a client looking to hire a team of developers

- [x] I want to be able to contact the developers by filling out and submitting a form by providing my name, email and message information so that the team have sufficient information to contact me afterwards

+ As a client looking to hire a team of developers

- [x] I want to click on a navigation link and a corresponding section be made visible in the browser window on the same page so that I can quickly navigate around the site without having to wait for new pages to be loaded.

+ As a client looking to hire a team of developers

- [x] I want to easily view the site when browsing on my mobile, tablet or desktop so that I can understand the sites content easily on whatever device I choose to view it in.

+ As a visually impaired client...

- [x] I would like to easily read and understand the text on your site so I can understand the information available

+ As a blind client...

- [x] would like to easily understand how to navigate the site after my screen reader reads me the content of the site so I can understand the information available.

+ As a client with JavaScript disabled in their browser for security reasons

- [x] I would like to visit your site and get a similar experience to viewing your site on a modern browser with JavaScript enabled so that I don't feel like I'm completely in the stone age.

**Comment by oliverjam** [comment]
Woo, all done 🎉
